using System.Linq;
using System.Numerics;
using Content.Shared.CMU14.ThreeD;
using Content.Client.CMU14.ThreeD.Scene;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.CMU14.ThreeD;

[GenerateTypedNameReferences]
public sealed partial class CMU3DPreviewWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    private CMU3DModelPrototype[] _models;
    private CMU3DModelPrototype? _model;
    private IDirectionalTextureProvider? _reference;
    private Direction _direction = Direction.South;
    private string[] _referenceSources = [];

    public CMU3DPreviewWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        SetSize = Vector2.Clamp(UserInterfaceManager.RootControl.Size - new Vector2(24), MinSize, new Vector2(1000, 680));
        _models = _prototypes.EnumeratePrototypes<CMU3DModelPrototype>()
            .OrderBy(model => model.Label, StringComparer.OrdinalIgnoreCase).ToArray();
        for (var i = 0; i < _models.Length; i++)
            Models.AddItem(_models[i].Label, i);
        Count.Text = Loc.GetString("cmu-3d-count", ("count", _models.Length));
        Models.OnItemSelected += args => SelectModel(args.Id);
        References.OnItemSelected += args => SelectReference(args.Id);
        AddDirection(Direction.South, "cmu-3d-south");
        AddDirection(Direction.East, "cmu-3d-east");
        AddDirection(Direction.North, "cmu-3d-north");
        AddDirection(Direction.West, "cmu-3d-west");
        DirectionSelection.SelectId((int) _direction);
        DirectionSelection.OnItemSelected += args =>
        {
            _direction = (Direction) args.Id;
            DirectionSelection.SelectId(args.Id);
            View.SetDirection(_direction);
            RefreshReference();
        };
        Reset.OnPressed += _ =>
        {
            _direction = Direction.South;
            DirectionSelection.SelectId((int) _direction);
            View.ResetCamera();
            RefreshReference();
        };
        Edges.OnToggled += args => View.ShowEdges = args.Pressed;
        if (_models.Length > 0)
            SelectModel(0);
        else
        {
            Models.Disabled = true;
            References.Disabled = true;
            Details.SetMessage(Loc.GetString("cmu-3d-empty"));
        }
    }

    public void ReleaseResources()
    {
        _models = [];
        _model = null;
        _reference = null;
        _referenceSources = [];
        ReferenceIcon.Texture = null;
        View.ReleaseResources();
    }

    public bool SelectModel(string id)
    {
        for (var i = 0; i < _models.Length; i++)
        {
            if (_models[i].ID != id)
                continue;
            SelectModel(i);
            return true;
        }
        return false;
    }

    private void AddDirection(Direction direction, string key) => DirectionSelection.AddItem(Loc.GetString(key), (int) direction);

    private void SelectModel(int id)
    {
        if (id < 0 || id >= _models.Length)
            return;
        _model = _models[id];
        Models.SelectId(id);
        View.SetModel(_model);
        Edges.Disabled = !View.SupportsEdges;
        View.SetDirection(_direction);
        ModelId.Text = _model.ID;
        ModelId.ToolTip = _model.ID;
        Details.SetMessage(Loc.GetString(View.WithinBudget ? "cmu-3d-details" : "cmu-3d-too-complex",
            ("status", _model.Status), ("parts", View.PartCount)));
        Description.SetMessage(_model.Description);
        References.Clear();
        _reference = null;
        ReferenceIcon.Texture = null;
        ReferenceIcon.Modulate = _model.ReferenceTint;
        _referenceSources = _model.SourcePrototypes.Length > 0 ? _model.SourcePrototypes :
            _model.ReferencePrototype is { } source ? [source] : [];
        References.Disabled = _referenceSources.Length == 0;
        for (var i = 0; i < _referenceSources.Length; i++)
            References.AddItem(_referenceSources[i], i);
        if (_referenceSources.Length > 0)
            SelectReference(0);
        else
            ReferenceStatus.SetMessage(Loc.GetString("cmu-3d-no-reference"));
    }

    private void SelectReference(int id)
    {
        if (_model == null || id < 0 || id >= _referenceSources.Length)
            return;
        References.SelectId(id);
        var source = _referenceSources[id];
        References.ToolTip = source;
        _reference = null;
        if (_model.ReferenceRsi is { } rsi && _model.ReferenceState is { } state)
            _reference = _entities.System<SpriteSystem>().RsiStateLike(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
        else if (_prototypes.TryIndex<EntityPrototype>(source, out var prototype) &&
            (prototype.Components.ContainsKey("Icon") || prototype.Components.ContainsKey("Sprite")))
        {
            _reference = _entities.System<SpriteSystem>().GetPrototypeIcon(prototype);
        }
        ReferenceStatus.SetMessage(Loc.GetString(_reference != null ? "cmu-3d-reference-ready" : "cmu-3d-reference-missing"));
        RefreshReference();
    }

    private void RefreshReference() => ReferenceIcon.Texture = _reference?.TextureFor(
        _model == null ? _direction : CMU3DSceneLayout.ReferenceDirection(_model, _direction));
}
