- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMSMESMachineCircuitboard
  name: SMES 机器电路板
  description: 用于SMES的机器印刷电路板。
  components:
  - type: Sprite
    state: power_mod
  - type: MachineBoard
    prototype: CMSMESEmpty
#    requirements:
#      Capacitor: 1
#      PowerCell: 4
#    materialRequirements:
#      CableHV: 10

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMAutolatheMachineCircuitboard
  name: 自动车床机器电路板
  description: 用于自动车床的机器印刷电路板
  components: # TODO RMC14 autolathe
  - type: MachineBoard
    prototype: RMCAutolatheEmpty
#      requirements:
#        MatterBin: 3
#        Manipulator: 1
#      materialRequirements:
#        CMGlass: 1

- type: entity
  parent: CMBaseMachineCircuitboard
  id: RMCPortableGeneratorPacmanMachineCircuitBoard
  name: P.A.C.M.A.N.型便携式发电机机器板
  components:
  - type: Sprite
    state: power_mod
  - type: MachineBoard
    prototype: RMCPortableGenerator
# TODO RMC14 material requirements
#		/obj/item/stock_parts/matter_bin = 1,
#		/obj/item/stock_parts/micro_laser = 1,
#		/obj/item/stack/cable_coil = 2,
#		/obj/item/stock_parts/capacitor = 1,

- type: entity
  parent: CMBaseMachineCircuitboard
  id: RMCPortableGeneratorSuperPacmanMachineCircuitboard
  name: S.U.P.E.R.P.A.C.M.A.N.型便携式发电机机器板
  components:
  - type: Sprite
    state: power_mod
  - type: MachineBoard
    prototype: RMCPortableGenerator2
# TODO RMC14 material requirements
#		/obj/item/stock_parts/matter_bin = 1,
#		/obj/item/stock_parts/micro_laser = 1,
#		/obj/item/stack/cable_coil = 2,
#		/obj/item/stock_parts/capacitor = 1,

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserChem
  name: 化学品分配器机器电路板
  description: 一种用于化学品分配器的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: RMCChemDispenserGround
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserBooze
  name: 酒水分配机电路板
  description: 用于酒水分配机的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMDispenserBoozeEmpty
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserSoda
  name: 汽水机电路板
  description: 用于汽水机的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMDispenserSoda
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardChemMaster
  name: 化学大师机器电路板
  description: 用于化学大师的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMChemMaster
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: RMCCircuitboardIndustrialChemMaster
  name: 化学大师机器板
  description: 用于工业化学大师的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: RMCChemMasterIndustrial
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardMicrowave
  name: 微波炉机器电路板
  description: 用于微波炉的机器印刷电路板。
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMMicrowave
#    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: RMCArmylatheMachineCircuitboard
  name: 军用车床机器电路板
  description: 用于军用车床的机器印刷电路板
  components:
  - type: MachineBoard
    prototype: RMCArmylatheEmpty

# - type: entity
#   parent: CMBaseMachineCircuitboard
#   id: RMCCircuitboardFireAlarm
#   name: fire alarm machine board
#   description: A machine printed circuit board for a fire alarm
#   components:
#     - type: MachineBoard
#       prototype: RMCFireAlarm # TODO RMC14 Fire Alarm

# - type: entity
#   parent: CMBaseMachineCircuitboard
#   id: RMCCircuitboardComputer
#   name: computer circuit board
#   description: A machine printed circuit board for a computer
#   components:
#     - type: MachineBoard
#       prototype: RMCComputer # TODO RMC14 Computer building

# - type: entity
#   parent: DoorElectronics
#   id: RMCElectronicsAirlock
#   name: airlock electronics
#   description: A machine printed circuit board for an airlock # TODO RMC14 Airlock Building
