using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ThreeD.Scene;

[GenerateTypedNameReferences]
public sealed partial class CMU3DLiveSceneWindow : DefaultWindow
{
    public event Action? SettingsChanged;

    public CMU3DLiveSceneWindow()
    {
        RobustXamlLoader.Load(this);
        SetSize = Vector2.Clamp(UserInterfaceManager.RootControl.Size - new Vector2(24), MinSize, new Vector2(960, 680));
        Reset.OnPressed += _ => View.ResetCamera();
        Top.OnPressed += _ => View.SetTopDown();
        Inherited.OnToggled += _ => SettingsChanged?.Invoke();
        Fallbacks.OnToggled += _ => SettingsChanged?.Invoke();
        Cutaway.OnToggled += _ => SettingsChanged?.Invoke();
    }
}
