using Content.Shared.CMU14.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ThreeD.Scene;

[GenerateTypedNameReferences]
public sealed partial class CMU3DCaptureWindow : DefaultWindow
{
    [Dependency] private IInputManager _input = default!;

    public event Action? StartRequested;
    public event Action? ChangeBindingRequested;

    public CMU3DCaptureWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Instructions.SetMessage(Loc.GetString("cmu-3d-capture-instructions",
            ("key", _input.GetKeyFunctionButtonString(CMUKeyFunctions.CMUToggleFirstPersonMouse))));
        StartLook.OnPressed += _ => StartRequested?.Invoke();
        ChangeBinding.OnPressed += _ => ChangeBindingRequested?.Invoke();
    }
}
