using System.Linq;
using System.Text;
using Content.Client._RMC14.Vendors;
using Content.Shared.CMU14.Requisitions.StockConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static System.StringComparison;

namespace Content.Client.CMU14.Requisitions.StockConsole;

/// <summary>
/// Read-only copy of the automated requisitions vendor window: the same sections, sprites and framed rows, with
/// how many of each item the vendors on this ship have left.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CMURequisitionsStockConsoleWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    private static readonly Color VendorHeaderColor = Color.FromHex("#4972A1");

    // Rows are kept between refreshes so the scroll position and search survive the automatic updates.
    private readonly List<(CMAutomatedVendorEntry Entry, Label Count)> _rows = new();
    private string? _layoutKey;

    public event Action? OnRefresh;

    public CMURequisitionsStockConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        Search.OnTextChanged += args => ApplySearchFilter(args.Text);
    }

    public void UpdateState(CMURequisitionsStockConsoleBuiState state)
    {
        var layoutKey = GetLayoutKey(state);
        if (layoutKey != _layoutKey)
        {
            _layoutKey = layoutKey;
            Rebuild(state);
        }

        var items = 0;
        var empty = 0;
        var row = 0;
        foreach (var vendor in state.Vendors)
        {
            foreach (var section in vendor.Sections)
            {
                foreach (var item in section.Items)
                {
                    items++;
                    if (item.Amount is <= 0)
                        empty++;

                    if (row < _rows.Count)
                        UpdateRow(_rows[row], item);

                    row++;
                }
            }
        }

        SummaryLabel.Text = Loc.GetString("cmu-req-stock-console-summary",
            ("vendors", state.Vendors.Count), ("items", items), ("empty", empty));
    }

    private void Rebuild(CMURequisitionsStockConsoleBuiState state)
    {
        Sections.DisposeAllChildren();
        _rows.Clear();

        if (state.Vendors.Count == 0)
        {
            Sections.AddChild(new Label
            {
                Text = Loc.GetString("cmu-req-stock-console-no-vendors"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 15, 0, 0),
            });
            return;
        }

        foreach (var vendor in state.Vendors)
        {
            // With more than one vendor on the ship, label whose stock each block of sections is.
            if (state.Vendors.Count > 1)
            {
                var header = new RichTextLabel { Margin = new Thickness(0, 15, 0, 0) };
                var message = new FormattedMessage();
                message.PushColor(VendorHeaderColor);
                message.AddMarkupOrThrow($"[bold]{FormattedMessage.EscapeText(vendor.Name.ToUpperInvariant())}[/bold]");
                message.Pop();
                header.SetMessage(message);
                Sections.AddChild(header);
            }

            foreach (var section in vendor.Sections)
            {
                var uiSection = new CMAutomatedVendorSection();
                var name = new FormattedMessage();
                name.AddMarkupOrThrow($"[bold]{FormattedMessage.EscapeText(section.Name.ToUpperInvariant())}[/bold]");
                uiSection.Label.SetMessage(name);

                foreach (var item in section.Items)
                {
                    var uiEntry = BuildEntry(item);
                    uiSection.Entries.AddChild(uiEntry.Entry);
                    _rows.Add(uiEntry);
                }

                Sections.AddChild(uiSection);
            }
        }

        ApplySearchFilter(Search.Text);
    }

    private (CMAutomatedVendorEntry Entry, Label Count) BuildEntry(CMURequisitionsStockItem item)
    {
        var uiEntry = new CMAutomatedVendorEntry();
        uiEntry.Panel.Button.TextLabel.Text = item.Name;

        // Nothing here can be vended, so the rows don't light up on hover.
        uiEntry.Panel.HoveredColor = CMAutomatedVendorPanel.DefaultColor;

        if (_prototypes.TryIndex<EntityPrototype>(item.Id, out var entity))
        {
            uiEntry.Texture.Textures = _entities.System<SpriteSystem>().GetPrototypeTextures(entity)
                .Select(o => o.Default)
                .ToList();

            if (entity.TryComp<SpriteComponent>(out var sprite, _entities.ComponentFactory) &&
                sprite.AllLayers.FirstOrDefault() is { } firstLayer)
            {
                uiEntry.Texture.Modulate = firstLayer.Color;
            }

            uiEntry.TooltipLabel.ToolTip = entity.Description;
            uiEntry.TooltipLabel.TooltipDelay = 0;
        }
        else
        {
            uiEntry.TooltipLabel.Visible = false;
        }

        return (uiEntry, uiEntry.Amount);
    }

    private static void UpdateRow((CMAutomatedVendorEntry Entry, Label Count) row, CMURequisitionsStockItem item)
    {
        var (entry, count) = row;
        var empty = item.Amount is <= 0;

        count.Text = item.Amount?.ToString() ?? Loc.GetString("rmc-vending-stock-infinite");
        count.Modulate = empty ? Color.Red : Color.White;

        entry.Stock.Visible = item.Max is > 0;
        if (item.Max is { } max && max > 0)
        {
            entry.Stock.Text = Loc.GetString("cmu-req-stock-console-of-max", ("max", max));
            entry.Stock.Modulate = empty ? Color.Red : Color.White;
        }

        entry.Panel.Button.Disabled = empty;
    }

    private void ApplySearchFilter(string? text)
    {
        foreach (var child in Sections.Children)
        {
            if (child is not CMAutomatedVendorSection section)
                continue;

            var any = false;
            foreach (var entryControl in section.Entries.Children)
            {
                if (entryControl is not CMAutomatedVendorEntry entry)
                    continue;

                entry.Visible = string.IsNullOrWhiteSpace(text) ||
                                (entry.Panel.Button.TextLabel.Text?.Contains(text, OrdinalIgnoreCase) ?? false);
                any |= entry.Visible;
            }

            section.Visible = any;
        }
    }

    private static string GetLayoutKey(CMURequisitionsStockConsoleBuiState state)
    {
        var key = new StringBuilder();
        foreach (var vendor in state.Vendors)
        {
            key.Append(vendor.Name).Append('|');
            foreach (var section in vendor.Sections)
            {
                key.Append(section.Name).Append(':');
                foreach (var item in section.Items)
                {
                    key.Append(item.Id).Append(',');
                }
            }
        }

        return key.ToString();
    }
}
