- type: entity
  parent: MarkerBase
  id: RMCSpawnerCorpse
  name: 尸体生成器——未知 | Corpse Spawner - Unknown
  suffix: RMC
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    layers:
    - state: corpse_spawner
  - type: CorpseSpawner
    spawn: RMCCorpse
