using Content.Shared.Access.Systems;
using Content.Shared.CMU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AU14CashVendorWindow : FancyWindow
{
    public event Action<int>? OnBuyPressed;
    public event Action? OnScanIdPressed;

    private AU14CashVendorBuiState? _lastState;
    private readonly IPrototypeManager _protoManager;
    private readonly IEntityManager _entManager;
    private readonly IPlayerManager _player;

    public AU14CashVendorWindow()
    {
        RobustXamlLoader.Load(this);
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        _entManager = IoCManager.Resolve<IEntityManager>();
        _player = IoCManager.Resolve<IPlayerManager>();
        SearchBar.OnTextChanged += _ => RefreshList();
        ScanIdBtn.OnPressed += _ => OnScanIdPressed?.Invoke();
    }

    public void UpdateState(AU14CashVendorBuiState state)
    {
        _lastState = state;
        InsertedCashLabel.Text = Loc.GetString("cash-vendor-amount", ("amount", state.InsertedCash.ToString("F0")));
        ReturnChangeBtn.Disabled = state.InsertedCash <= 0;
        TaxFooterLabel.Text = state.SalesTaxPercent > 0
            ? Loc.GetString("cash-vendor-sales-tax", ("percent", state.SalesTaxPercent.ToString("F0")))
            : Loc.GetString("cash-vendor-no-sales-tax");

        ScanIdBtn.Visible = state.AllowDepartmentBudget;
        ScanIdBtn.Text = state.HasDepartmentMode
            ? Loc.GetString("cash-vendor-clear-department")
            : Loc.GetString("cash-vendor-scan-id");

        var cardBalance = GetCardBalance();
        IdAccountRow.Visible = !state.HasDepartmentMode && cardBalance != null;
        if (cardBalance is { } balance)
            IdAccountLabel.Text = Loc.GetString("cash-vendor-amount", ("amount", balance));

        DeptBudgetRow.Visible = state.HasDepartmentMode;
        if (state.HasDepartmentMode)
        {
            DeptBudgetLabel.Text = Loc.GetString(
                "cash-vendor-department-budget-value",
                ("amount", state.DepartmentBudget.ToString("F0")),
                ("department", state.DepartmentName));
        }

        RefreshList();
    }

    private void RefreshList()
    {
        ItemList.RemoveAllChildren();

        if (_lastState == null)
            return;

        var filter = SearchBar.Text?.Trim() ?? string.Empty;
        // Inserted cash is spent first, the rest comes off the ID card the player is carrying.
        var available = _lastState.InsertedCash + (GetCardBalance() ?? 0);

        foreach (var item in _lastState.Items)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !item.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                HorizontalExpand = true
            };

            if (_protoManager.HasIndex<EntityPrototype>(item.ItemProtoId))
            {
                var icon = new EntityPrototypeView
                {
                    MinSize = new System.Numerics.Vector2(32, 32),
                    VerticalAlignment = VAlignment.Center
                };
                icon.SetPrototype(item.ItemProtoId);
                row.AddChild(icon);
            }
            else
            {
                row.AddChild(new Robust.Client.UserInterface.Control { MinSize = new System.Numerics.Vector2(32, 32) });
            }

            var nameLabel = new Label
            {
                Text = item.Name,
                HorizontalExpand = true,
                ClipText = true,
                SizeFlagsStretchRatio = 3
            };

            var priceLabel = new Label
            {
                Text = Loc.GetString("cash-vendor-amount", ("amount", item.EffectivePrice)),
                MinWidth = 40,
                HorizontalAlignment = HAlignment.Right
            };

            var canAfford = _lastState.HasDepartmentMode
                ? _lastState.DepartmentBudget >= item.EffectivePrice
                : available >= item.EffectivePrice;

            var buyBtn = new Button { Text = Loc.GetString("cash-vendor-buy"), MinWidth = 50 };
            var idxCopy = item.Index;
            buyBtn.Disabled = !canAfford;
            buyBtn.OnPressed += _ => OnBuyPressed?.Invoke(idxCopy);

            row.AddChild(nameLabel);
            row.AddChild(priceLabel);
            row.AddChild(buyBtn);
            ItemList.AddChild(row);
        }

        if (ItemList.ChildCount == 0)
            ItemList.AddChild(new Label { Text = Loc.GetString("cash-vendor-no-items") });
    }

    /// <summary>The balance on the local player's ID card, or null if they don't have one on them.</summary>
    private int? GetCardBalance()
    {
        if (_player.LocalEntity is not { } player ||
            !_entManager.System<SharedIdCardSystem>().TryFindIdCard(player, out var card))
        {
            return null;
        }

        return card.Comp.AccountBalance;
    }
}
