#!/usr/bin/env python3
"""Generate/check native floor material prototypes from inventoried source PNGs.

Only alpha-weighted color averages are emitted, never source pixels. SourceSprite
and SourceMetadata retain the original resource and available attribution paths;
the generator does not assign a license to source art or derived material data.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

import inventory as art_inventory
from scene import enrich_materials

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "Content.CMU/Resources/ThreeD/Prototypes/World/tile_materials.yml"


def source_metadata(root: Path, reference: str) -> list[str]:
    path = art_inventory.resource_path(root, reference)
    if path is None:
        return []
    resource_roots = {root / "Content.CMU/Resources", root / "Resources"}
    references = set()
    folder = path.parent
    while folder not in resource_roots and folder != root and folder != folder.parent:
        for name in ("meta.json", "LICENSE", "LICENSE.txt", "LICENSE.md", "ATTRIBUTION.md", "COPYING"):
            candidate = folder / name
            if candidate.is_file():
                references.add(candidate.relative_to(root).as_posix())
        folder = folder.parent
    return sorted(references)


def build_materials(root: Path, inventory: dict) -> tuple[list[dict], dict]:
    palette = {}
    skipped = []
    for tile in sorted(inventory.get("tiles", []), key=lambda item: item["id"]):
        if not isinstance(tile.get("sprite"), str) or not tile["sprite"]:
            skipped.append(tile["id"])
            continue
        palette[tile["id"]] = {"prototype": tile["id"], "sprite": tile["sprite"], "variants": tile.get("variants", 1)}
    scene = {"tilePalette": palette, "sourceReferences": {}, "diagnostics": {"limitations": []}}
    enrich_materials(scene, root)
    errors = scene["diagnostics"]["materialErrors"]
    if errors:
        raise ValueError("Tile material sampling failed: " + json.dumps(errors, ensure_ascii=False))
    materials = []
    for tile_id, entry in palette.items():
        reference = art_inventory.texture_reference(entry["sprite"])
        materials.append({"type": "cmu3DTileMaterial", "id": "CMU3DTile" + tile_id, "tile": tile_id,
                          "colors": entry["variantColors"], "sourceSprite": reference,
                          "sourceMetadata": source_metadata(root, reference),
                          "description": "Approximate alpha-weighted average of each 32x32 source tile variant. "
                                         "Preserves source resource references; no license is assigned by this generator."})
    return materials, {"materials": len(materials), "variantColors": sum(len(item["colors"]) for item in materials),
                       "skippedTilesWithoutSprite": skipped}


def render_yaml(materials: list[dict]) -> bytes:
    header = ("# Generated by python Tools/three_d/build_tile_materials.py; do not edit by hand.\n"
              "# Average source colors only. Source sprite files and existing attribution retain their original terms.\n"
              "# Colors approximate textures; they are not a fidelity approval or replacement sprite artwork.\n\n")
    return (header + yaml.safe_dump(materials, sort_keys=False, allow_unicode=True, width=110)).encode("utf-8")


def write_or_check(path: Path, expected: bytes, check: bool) -> None:
    if check:
        if not path.is_file() or path.read_bytes() != expected:
            raise ValueError(f"Stale or missing generated tile materials: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(expected)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--inventory", type=Path, default=ROOT / "Tools/three_d/generated/inventory.json")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="Verify generated bytes without changing any file")
    args = parser.parse_args()
    inventory = json.loads(args.inventory.read_text(encoding="utf-8"))
    try:
        materials, report = build_materials(args.root.resolve(), inventory)
        write_or_check(args.output, render_yaml(materials), args.check)
    except ValueError as error:
        raise SystemExit(str(error)) from error
    print(json.dumps({"checked": args.check, **report}, indent=2))


if __name__ == "__main__":
    main()
