"""Keep portable mesh, browser and native analytic leaf transforms identical."""
from pathlib import Path
import argparse
import json
from foliage import lobes

ROOT = Path(__file__).resolve().parents[2]
START = '// BEGIN GENERATED FOLIAGE TRANSFORMS'
END = '// END GENERATED FOLIAGE TRANSFORMS'


def outputs():
    data = list(lobes())
    js = '// Generated by Tools/three_d/generate_foliage.py; source: foliage.py.\n'
    js += 'export const FOLIAGE_LOBES = ' + json.dumps(data, separators=(',', ':')) + ';\n'
    cs = '// Generated by Tools/three_d/generate_foliage.py; source: foliage.py.\n'
    cs += 'using System.Numerics;\n\nnamespace Content.Client.CMU14.ThreeD.Scene;\n\n'
    cs += 'internal static partial class CMU3DFoliage\n{\n'
    cs += '    private static readonly (Vector3 Center, Vector3 X, Vector3 Y, Vector3 Z)[] Leaves =\n    [\n'
    shader = [START, 'void foliageTransform(highp float index, out highp vec3 center, out highp vec3 ax, out highp vec3 ay, out highp vec3 az) {']
    for i, (center, axes, size) in enumerate(data):
        rows = [tuple(2*v/size[j] for v in axes[j]) for j in range(3)]
        vector = lambda v: 'new(' + ', '.join(f'{x:.10f}f' for x in v) + ')'
        cs += '        (' + ', '.join(vector(v) for v in (center, *rows)) + '),\n'
        glvector = lambda v: 'vec3(' + ', '.join(f'{x:.10f}' for x in v) + ')'
        shader.append(f'    {"if" if i == 0 else "else if"} (index == {i}.0) {{')
        for name, v in zip(('center', 'ax', 'ay', 'az'), (center, *rows)):
            shader.append(f'        {name} = {glvector(v)};')
        shader.append('    }')
    shader.extend(['    else { center = vec3(0.0); ax = vec3(1.0, 0.0, 0.0); ay = vec3(0.0, 1.0, 0.0); az = vec3(0.0, 0.0, 1.0); }', '}', END])
    cs += '    ];\n}\n'
    path = ROOT/'Content.CMU/Resources/Textures/CMU14/Interface/three_d_scene.swsl'
    source = path.read_text(encoding='utf-8')
    block = '\n'.join(shader)
    if START in source:
        before, rest = source.split(START, 1)
        _, after = rest.split(END, 1)
        source = before + block + after
    else:
        source = source.replace('highp float intersectBox(', block+'\n\nhighp float intersectBox(', 1)
    return {ROOT/'Tools/three_d/viewer/foliage-data.js': js,
            ROOT/'Content.CMU/Client/ThreeD/Scene/CMU3DFoliage.Data.cs': cs,
            path: source}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Stale foliage transforms: {path}')
        else:
            path.write_text(content, encoding='utf-8')
    print('Foliage transforms ' + ('verified.' if args.check else 'generated.'))
