using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.UserInterface.Options;

[GenerateTypedNameReferences]
public sealed partial class VoicelinesTab : Control
{
    public VoicelinesTab()
    {
        RobustXamlLoader.Load(this);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesYourself, RMCVoicelinesYourself);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesYourself, RMCEmotesYourself);

        // cmu edit: only humans are playable, other species' voiceline and emote options removed
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesHuman, RMCVoicelinesHuman);

        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesHuman, RMCEmotesHuman);
    }
}
