using Content.Shared.CMU14.Expeditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Expeditions;

[GenerateTypedNameReferences]
public sealed partial class CMUSquadPanelWindow : DefaultWindow
{
    public CMUSquadPanelWindow() => RobustXamlLoader.Load(this);
}
